#!/usr/bin/env python3
"""Build and install Shaarli's stock and site CSS as one stylesheet."""

import argparse
import hashlib
import os
import re
import stat
import tempfile
from pathlib import Path


BUNDLE_NAME = "site-refined.css"

STOCK_STYLES = """\
<link type="text/css" rel="stylesheet" href="{$asset_path}/css/shaarli.min.css?v={$version_hash}#" />
{if="strpos($formatter, 'markdown') !== false"}
  <link type="text/css" rel="stylesheet" href="{$asset_path}/css/markdown.min.css?v={$version_hash}#" />
{/if}
"""

USER_STYLES = """\
{if="is_file('data/user.css')"}
  <link type="text/css" rel="stylesheet" href="{$root_path}/data/user.css#" />
{/if}
"""

MANAGED_LINK_RE = re.compile(
    r'<link type="text/css" rel="stylesheet" '
    r'href="\{\$asset_path\}/css/site-refined\.css\?v=[0-9a-f]{16}#" />'
)
FORKAWESOME_START = "/*!\nFork Awesome "
SHAARLI_THEME_START = ":root{--main-color:"


def remove_forkawesome_css(css: str) -> str:
    starts = [match.start() for match in re.finditer(re.escape(FORKAWESOME_START), css)]
    theme_starts = [
        match.start() for match in re.finditer(re.escape(SHAARLI_THEME_START), css)
    ]
    if len(starts) != 1 or len(theme_starts) != 1 or starts[0] >= theme_starts[0]:
        raise ValueError(
            "could not isolate the ForkAwesome block in Shaarli CSS"
        )
    return css[: starts[0]] + css[theme_starts[0] :]


def build_bundle(stock: str, markdown: str, refined: str) -> str:
    stock = remove_forkawesome_css(stock)
    sections = (
        ("Shaarli base styles", stock),
        ("Shaarli Markdown styles", markdown),
        ("mihaicosma.com refinements", refined),
    )
    rendered = ["/* Generated by build_css_bundle.py. Do not edit. */"]
    for label, content in sections:
        rendered.extend((f"\n/* {label} */", content.strip()))
    return "\n".join(rendered) + "\n"


def patch_includes(content: str, digest: str) -> tuple[str, bool]:
    link = (
        '<link type="text/css" rel="stylesheet" '
        f'href="{{$asset_path}}/css/{BUNDLE_NAME}?v={digest}#" />'
    )

    managed = MANAGED_LINK_RE.findall(content)
    if managed:
        if len(managed) != 1 or STOCK_STYLES in content or USER_STYLES in content:
            raise ValueError("Shaarli stylesheet template has conflicting managed links")
        patched = MANAGED_LINK_RE.sub(link, content)
        return patched, patched != content

    if content.count(STOCK_STYLES) != 1 or content.count(USER_STYLES) != 1:
        raise ValueError(
            "Shaarli includes template changed upstream; refusing to replace "
            "its stylesheet links"
        )

    patched = content.replace(STOCK_STYLES, "").replace(USER_STYLES, link + "\n")
    return patched, True


def atomic_write(path: Path, content: str, reference: Path) -> None:
    reference_stat = reference.stat()
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", text=True
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, stat.S_IMODE(reference_stat.st_mode))
        os.chown(temporary, reference_stat.st_uid, reference_stat.st_gid)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def install(root: Path, refined_path: Path) -> tuple[Path, str, bool]:
    css_dir = root / "tpl/default/css"
    stock_path = css_dir / "shaarli.min.css"
    markdown_path = css_dir / "markdown.min.css"
    includes_path = root / "tpl/default/includes.html"
    bundle_path = css_dir / BUNDLE_NAME

    stock = stock_path.read_text(encoding="utf-8")
    markdown = markdown_path.read_text(encoding="utf-8")
    refined = refined_path.read_text(encoding="utf-8")
    includes = includes_path.read_text(encoding="utf-8")

    bundle = build_bundle(stock, markdown, refined)
    digest = hashlib.sha256(bundle.encode()).hexdigest()[:16]
    patched_includes, template_changed = patch_includes(includes, digest)

    if not bundle_path.exists() or bundle_path.read_text(encoding="utf-8") != bundle:
        atomic_write(bundle_path, bundle, stock_path)
    if template_changed:
        atomic_write(includes_path, patched_includes, includes_path)

    return bundle_path, digest, template_changed


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path, help="Shaarli installation root")
    parser.add_argument("refined", type=Path, help="site refinement stylesheet")
    args = parser.parse_args()

    bundle, digest, changed = install(args.root, args.refined)
    action = "patched template" if changed else "template already current"
    print(f"installed {bundle} ({digest}); {action}")


if __name__ == "__main__":
    main()
